apiVersion: v1
kind: Namespace
metadata:
  name: ewp
  labels:
    istio-injection: enabled
    app.kubernetes.io/managed-by: github-actions
    pod-security.kubernetes.io/enforce: privileged
    pod-security.kubernetes.io/warn: privileged
    pod-security.kubernetes.io/audit: privileged
