apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: ewp-server-vs
  namespace: ewp
spec:
  hosts:
    - "ewp.${TEST_DOMAIN}"
  gateways:
    - ewp-gateway
  http:
    - name: "route-grpc"
      match:
        - headers:
            content-type:
              prefix: "application/grpc"
      route:
        - destination:
            host: ewp-server.ewp.svc.cluster.local
            port:
              number: 8080
            subset: grpc-upstream
